name:                chip8
version:             0.0.1.0
github:              "nixant/chip8"
license:             BSD3
author:              "Nishant Kaushik"
maintainer:          "nixantkaushik@gmail.com"
copyright:           "2021 Nishant Kaushik"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/nixant/chip8#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- data-default
- stm
- mtl

library:
  source-dirs: src

executables:
  chip8:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chip8

tests:
  chip8-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chip8
